import Head from 'next/head'
import Note from '../components/Note'

export default function Home() {
  return (
    <>
      <Head>
        <title>Random Music Note Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Note/>
      </main>
    </>
  )
}
